name: Build wg-autoconf APK
on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'src/**'
      - 'APKBUILD'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup APK build environment
        run:
          apk add --no-cache alpine-sdk abuild

      - name: Setup signing keys
        run: |
          mkdir -p ~/.abuild
          echo "${{ secrets.RSA_PRIVATE_KEY }}" > ~/.abuild/wg-autoconf.rsa
          echo "${{ secrets.RSA_PUBLIC_KEY }}" > ~/.abuild/wg-autoconf.rsa.pub
          cp ~/.abuild/wg-autoconf.rsa.pub /etc/apk/keys/
          chmod 600 ~/.abuild/wg-autoconf.rsa
          chmod 644 ~/.abuild/wg-autoconf.rsa.pub
          printf 'PACKAGER_PRIVKEY=%s/.abuild/wg-autoconf.rsa\nPACKAGER="Alexander Gomez <alexandrglm@proton.me>"\n' "$HOME" > ~/.abuild/abuild.conf

      - name: Build APK
        run: |
          git config --global --add safe.directory "$(pwd)"
          abuild -F checksum
          abuild -F -r

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep "^pkgver=" APKBUILD | cut -d= -f2 | tr -d '"')
          REL=$(grep "^pkgrel=" APKBUILD | cut -d= -f2 | tr -d '"')
          echo "VERSION=${VERSION}-r${REL}" >> $GITHUB_OUTPUT

      - name: Copy public key to workspace
        run: cp ~/.abuild/wg-autoconf.rsa.pub ./wg-autoconf.rsa.pub

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: wg-autoconf - v.${{ steps.get_version.outputs.VERSION }} - Stable Release
          body: |
            This release contains sources for **wg-autoconf v1.0.0**, a stable release intended for inclusion in OpenWrt's official package repositories (PR pending).
            **Compatibility:** Intended for OpenWrt **25.12+** `.apk` (Alpine SDK) only.
            Please, check [README](https://github.com/alexandrglm/openwrt_wg-autoconf/blob/main/README.md) (and [DOCS.md](https://github.com/alexandrglm/openwrt_wg-autoconf/blob/main/DOCS.md)) from the main branch.
            ----
            ## Changelog
            ## From 0.0.1-r6 / 0.0.1-r7 to 1.0.0-r1 main
            - [X] - Refactor NFT subsystem
            - [X] - Add selective IP leak blocking (WITHOUT REQUIRING a `/etc/init.d/network restart`!!!)
            - [X] - Add IPv6 full routing support (IPv4/IPv6/Dual Stack modes)
            - [X] **Downgrade versions to `0.0.1-rX` until the final version for inclusion in the OpenWRT repositories is finalised, with that latter being `1.0.0-r1`**
            - [X] - Added a flag-method to replace APK lifecycle methods. Logic to prevent "disasters" is now more robust, depending on the binary itself rather than `apk add`/`apk del`/`apk add --upgrade` actions.
            - [X] - Refactored cleanup and "nuke" functions into a single centralised function
            - [X] - Refactored the `setup` functions, merging "auto" and `--advanced` modes into one
            - [X] - Cleaned up other `debug_*` tags than the enabled debug function itself
            - [X] - `list_configs`, `list_configs_full`: Improve usability
            - [X] - Unified syntax:  Ternaries, Arrays destructuring, `echo` and `read -p` VS `printf`, POSIX/REGEX --> Test on many different Busybox-Ash shells
            - [X] - Add WG Server support
            - [X] - Add fully IPv6 support
            - [X] - Add DNS leakage notice
            - [X] - Add DNS resolv pre-checks for auto and `--advanced` mode
            - [X] - Fix CLI-UI:   `ui_lines`, CLI colours, for a better CLI - UI
            ### From 0.0.1-r5
            - Migrated APK build SDK to `docker:alpine:latest`, improving build reproducibility and isolation.
            - Added debugging capabilities via dedicated `debug` commands.
            - Fixed issues in APK lifecycle scripts (pre_inst, post_inst, pre_rm hooks).
            - Improved backup and restore of `etc/config/...` by adding checksum and tag validation.
            ### From 0.0.1.-r4
            - Fixed `unset_lan_routes()` logic: previous implementation did not correctly clean routing tables assigned in `/etc/iproute2/rt_tables`.
            - Improved overall verbosity `--verbose` mode.
            - Moved APK lifecycle methods (pre/post install/remove) from `APKBUILD` / `Makefile` into dedicated scripts, simplifying packaging and repository maintenance.
          files: |
            /github/home/packages/**/*.apk
            wg-autoconf.rsa.pub
          prerelease: false
          draft: false

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wg-autoconf-apk
          path: /github/home/packages/**/*.apk
          if-no-files-found: error
